### ISSUE TITLE
running on travis

### ISSUE THREAD

**Issue by physikerwelt** [djsutherland/arxiv-collector#8]
The program runs great on my local computer. However, when I tried to run it on the CI service Travis, only the main tex file and the bbl file were included. The image file included files and others included tex files were not included. Do you by chance have any experience to run the arxiv-collector from Travis?

**Comment by djsutherland** [comment]
I haven't tried it, but sounds like some issue with latexmk there. Try running with `--debug` and/or posting the output of `latexmk -pdf -deps WHATEVER.tex`, which is what this script parses to look at what should be included.

**Comment by physikerwelt** [comment]
I have created a pull request #9 that is not supposed to be merged but to demonstrate the problem. It would great if we could integrate your arxiv-collector to our open-science template https://github.com/ag-gipp/OpenScienceTemplate

**Comment by djsutherland** [comment]
It seems it was caused by a synctex message that doesn't end in a newline for some reason, so (depending on the local compilation state) the `Dependents` line that `arxiv-collector` looks for wasn't on its own line. This should be fixed in the new 0.2.3 release, but I'll of course reopen if not.

And you're of course welcome to use it in open-science template; let me know if there's anything I should change to make it easier for you, or you run into any other problems. :)

**Comment by physikerwelt** [comment]
the same problem remains with the current master branch
see
https://travis-ci.org/physikerwelt/arxiv-collector/builds/535311964#L2077-L2087

**Comment by djsutherland** [comment]
Ohhhh, huh. This is actually a weird different issue. Working on a fix now.

**Comment by djsutherland** [comment]
It's not what I thought at first – it actually seems to be that the most recent versions of latexmk have broken `-deps`. From http://personal.psu.edu/jcc8//software/latexmk-jcc/versions.html, it looks like it broke in between version 4.61 (last October) and 4.63b (last March). It's not something about your paper in particular, it happens even on a trivial test paper.

I'll report the bug to the author. In the meantime, maybe I'll bundle a version of latexmk with arxiv-collector or something....

**Comment by djsutherland** [comment]
The new 0.3.0 throws an error if the latexmk version is known broken, and has a utility to download a working version of latexmk. You can use it in your travis builds like this:
```
script:
  - cd test
  - arxiv-collector --get-latexmk latexmk
  - arxiv-collector --latexmk ./latexmk test.tex
```

**Comment by physikerwelt** [comment]
Thank you for your fix. However, Travis still refused to compile. 

https://travis-ci.org/physikerwelt/arxiv-collector/builds/537643156#L2064

Did I miss something in https://github.com/physikerwelt/arxiv-collector/commit/db89c6726a5c57af924ba3751039bb45ac67370a ? Or are there additional dependencies?


https://github.com/physikerwelt/arxiv-collector/blob/db89c6726a5c57af924ba3751039bb45ac67370a/.travis.yml#L15-L19

**Comment by djsutherland** [comment]
It was a python 2 error, fixed in 0.3.2 (and then another python 2 error, fixed in 0.3.3); try again?

You can also remove the plain `latexmk` line; it's not needed, though I don't think it'll break anything.

**Comment by physikerwelt** [comment]
I have the feeling that there are more python 2 errors. At least it still fails on Travis with python 2.7.

  works on Python 3, though-  That's fine with me.
See
https://travis-ci.org/physikerwelt/arxiv-collector/builds/540865849
for the details.
Maybe it would be a good idea to drop python 2 support officially?

**Comment by djsutherland** [comment]
Turned out to be because I didn't read properly or, for some reason, test, the "fix" in 0.3.3. This version actually works. Thanks again!

I should definitely set up CI here to avoid that happening in the future, but I think enough people use python 2 by default still that I should support it while it's relatively easy.
